

GET http://localhost:8080/users/search?query=n


###

PATCH  http://localhost:8080/users/56
Content-Type: application/json

{
    "code_number": "OPTECH",
    "status": true
}

###
POST http://localhost:8080/users
Content-Type: application/json

{
    "fullname": "THINKTODO",
    "email": "thinktodo@gmail.com",
    "phone_number": "+840123456",
    "status": true
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
    "code_number": "5ZJY7I",
    "password": "$2b$10$KBFX7yDNF9uuEu/Dv.j5xO"
}

###
DELETE  http://localhost:8080/logout