
GET http://localhost:8080/users/search?query=kien

PATCH  http://localhost:8080/users/55
Content-Type: application/json

{
    "status": false
}

###
POST http://localhost:8080/users
Content-Type: application/json

{
    "fullname": "Phus",
    "email": "phunobi1807@gmail.com",
    "phone_number": "12345671",
    "status": true
}

### 
POST http://localhost:8080/login
Content-Type: application/json

{
    "code_number": "3RVO2Y",
    "password": "$2b$10$H0.Zm9.DsTbYZtHFsn5Xuu"
}

###
DELETE  http://localhost:8080/logout